// Generated by CoffeeScript 1.12.7
(function() {
  var db, express, router;

  express = require('express');

  router = express.Router();

  db = require('./../libs/db');

  router.get('/faq', function(req, res, next) {
    return db.users.insert({
      test: '1'
    }, function(err, user) {
      if (err) {
        return next(err);
      }
      console.log(user);
      return res.send(user);
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=api.js.map
