// Generated by CoffeeScript 1.12.7
(function() {
  var express, router;

  express = require('express');

  router = express.Router();

  router.get('/faq', function(req, res, next) {
    return res.send('I\'m fine');
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=api.js.map
